#!/usr/bin/env python3
"""Regenerate the separated static and moving event-scene SVG spans."""

from __future__ import annotations

import argparse
import copy
import difflib
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import TypedDict, cast


class DraftLayer(TypedDict):
    name: str
    moving: bool
    frames: list[str]


class SplitPayload(TypedDict):
    sources: dict[str, str]
    layers: dict[str, list[DraftLayer]]


class CropMetadata(TypedDict):
    sources: dict[str, str]
    layers: dict[str, list[list[str | int | bool]]]


STEMS = ("burst_water_main", "burst_water_main_vertical", "car_accident", "car_accident_vertical")
TOOLS = Path(__file__).resolve().parent
PROJECT_ROOT = TOOLS.parent
CROP_HELPER = TOOLS / "split-scenes-crop.gd"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog="example: uv run python tools/split-scenes.py --check",
    )
    parser.add_argument(
        "--godot",
        default=os.environ.get("GODOT", "/Applications/Godot.app/Contents/MacOS/Godot"),
        help="Godot executable used to rasterize and crop the authored SVG spans",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare regenerated runtime outputs without writing them",
    )
    parser.add_argument(
        "--metadata-output",
        type=Path,
        help="explicitly write fresh crop/source metadata; ordinary maintenance leaves evidence records untouched",
    )
    return parser.parse_args()


def build_payload() -> SplitPayload:
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    sources: dict[str, str] = {}
    layers: dict[str, list[DraftLayer]] = {}
    for stem in STEMS:
        paths = [PROJECT_ROOT / "art/events" / f"{stem}{suffix}.svg" for suffix in ("", "_b")]
        scenes = [ET.parse(path).getroot() for path in paths]
        sources.update(
            {str(path.relative_to(PROJECT_ROOT)): hashlib.sha256(path.read_bytes()).hexdigest() for path in paths}
        )
        for scene in scenes:
            for element in scene:
                element.tail = None
        keys = [[ET.tostring(element) for element in scene] for scene in scenes]
        spans = difflib.SequenceMatcher(a=keys[0], b=keys[1], autojunk=False).get_opcodes()
        expected_spans = 7 if stem.startswith("burst") else 3
        if len(spans) != expected_spans:
            raise RuntimeError(f"{stem}: expected {expected_spans} painter-order spans, got {spans!r}")
        result: list[DraftLayer] = []
        for number, (operation, first_start, first_end, second_start, second_end) in enumerate(spans):
            moving = operation != "equal"
            name = f"{stem}_{'motion' if moving else 'static'}_{number}"
            documents: list[str] = []
            for frame, start, stop in (
                (0, first_start, first_end),
                (1, second_start, second_end),
            ):
                scene = scenes[frame]
                layer = ET.Element(scene.tag, scene.attrib)
                definitions = [element for element in scene if element.tag.endswith("}defs")]
                layer.extend(copy.deepcopy(definitions))
                layer.extend(
                    copy.deepcopy([element for element in list(scene)[start:stop] if not element.tag.endswith("}defs")])
                )
                documents.append(ET.tostring(layer, encoding="unicode"))
            result.append(
                {
                    "name": name,
                    "moving": moving,
                    "frames": documents if moving else documents[:1],
                }
            )
        layers[stem] = result
    return {"sources": sources, "layers": layers}


def crop_with_godot(godot: str, payload: SplitPayload, staging: Path) -> CropMetadata:
    input_path = staging / "split-input.json"
    metadata_path = staging / "layers.json"
    (staging / "art/events").mkdir(parents=True)
    input_path.write_text(json.dumps(payload))
    subprocess.run(
        [
            godot,
            "--headless",
            "--path",
            str(PROJECT_ROOT),
            "--script",
            str(CROP_HELPER),
            "--",
            str(input_path),
            str(staging),
            str(metadata_path),
        ],
        check=True,
    )
    return cast(CropMetadata, json.loads(metadata_path.read_text()))


def scenery_parts(metadata: CropMetadata) -> bytes:
    result = [
        "class_name EventSceneryParts",
        "extends RefCounted",
        "## Generated by tools/split-scenes.py; do not edit registered spans by hand.",
        "## The source SVG painter order and crop metadata are the editable inputs.",
        "",
        "const LAYERS := {",
    ]
    for stem, entries in metadata["layers"].items():
        result.append(f'\t"{stem}": [')
        for entry in entries:
            result.append("\t\t" + json.dumps(entry) + ",")
        result.append("\t],")
    result.append("}\n")
    return "\n".join(result).encode()


def membership(metadata: CropMetadata) -> bytes:
    membership_path = PROJECT_ROOT / "assets/atlases/membership.json"
    contents = cast(dict[str, object], json.loads(membership_path.read_text()))
    groups = cast(dict[str, object], contents["groups"])
    events = cast(dict[str, object], groups["events"])
    members = cast(list[str], events["members"])
    for entries in metadata["layers"].values():
        for entry in entries:
            name = str(entry[0])
            moving = bool(entry[5])
            for suffix in ("", "_b") if moving else ("",):
                path = f"art/events/{name}{suffix}.svg"
                if path not in members:
                    members.append(path)
    members.sort()
    return (json.dumps(contents, indent=2) + "\n").encode()


def runtime_outputs(staging: Path, metadata: CropMetadata) -> dict[Path, bytes]:
    outputs = {
        PROJECT_ROOT / "src/events/event_scenery_parts.gd": scenery_parts(metadata),
        PROJECT_ROOT / "assets/atlases/membership.json": membership(metadata),
    }
    for generated in (staging / "art/events").glob("*.svg"):
        outputs[PROJECT_ROOT / "art/events" / generated.name] = generated.read_bytes()
    expected_svg_count = sum(2 if bool(entry[5]) else 1 for entries in metadata["layers"].values() for entry in entries)
    actual_svg_count = len(outputs) - 2
    if actual_svg_count != expected_svg_count:
        raise RuntimeError(f"expected {expected_svg_count} generated SVGs, got {actual_svg_count}")
    return outputs


def check_outputs(outputs: dict[Path, bytes]) -> bool:
    different = [path for path, contents in outputs.items() if not path.is_file() or path.read_bytes() != contents]
    if different:
        for path in different:
            print(f"out of date: {path.relative_to(PROJECT_ROOT)}")
        return False
    print(f"scenery split outputs are current ({len(outputs)} files)")
    return True


def write_outputs(outputs: dict[Path, bytes]) -> None:
    for path, contents in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as temporary:
            temporary.write(contents)
            temporary_path = Path(temporary.name)
        temporary_path.replace(path)


def main() -> int:
    args = parse_args()
    godot: str = args.godot
    check: bool = args.check
    metadata_output: Path | None = args.metadata_output
    if check and metadata_output is not None:
        raise SystemExit("--check and --metadata-output cannot be combined")
    payload = build_payload()
    with tempfile.TemporaryDirectory(prefix="scenery-split-") as temporary:
        staging = Path(temporary)
        metadata = crop_with_godot(godot, payload, staging)
        outputs = runtime_outputs(staging, metadata)
        if check:
            return 0 if check_outputs(outputs) else 1
        write_outputs(outputs)
        if metadata_output is not None:
            destination = metadata_output if metadata_output.is_absolute() else PROJECT_ROOT / metadata_output
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(staging / "layers.json", destination)
            print(f"wrote explicit metadata record {destination}")
    print(f"registered {sum(len(entries) for entries in metadata['layers'].values())} ordered layers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
