extends SceneTree
## Crops separated vector spans with the runtime SVG parser and retains their registration.
## Invoked only by tools/split-scenes.py; its output directory is always a fresh staging folder.

const USAGE := """usage: Godot --headless --script tools/split-scenes-crop.gd -- INPUT STAGING METADATA

Crops the split-scene description in INPUT into the fresh STAGING directory and writes the
derived registration to METADATA. This helper is normally invoked by tools/split-scenes.py.
"""

func _init() -> void:
	var arguments := OS.get_cmdline_user_args()
	if arguments.size() == 1 and arguments[0] in ["--help", "-h"]:
		print(USAGE)
		quit()
		return
	var has_flag := false
	for argument in arguments:
		has_flag = has_flag or argument.begins_with("-")
	if arguments.size() != 3 or has_flag:
		printerr("split-scenes-crop.gd: expected INPUT STAGING METADATA")
		printerr(USAGE)
		quit(2)
		return
	var payload: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(arguments[0]))
	var staging: String = arguments[1]
	var metadata_path: String = arguments[2]
	var output := {"sources": payload.sources, "layers": {}}
	for stem: String in payload.layers:
		var entries: Array = []
		for layer: Dictionary in payload.layers[stem]:
			var bounds := Rect2i()
			var canvas := Rect2i()
			for source: String in layer.frames:
				var image := Image.new()
				assert(image.load_svg_from_string(source) == OK)
				canvas = Rect2i(Vector2i.ZERO, image.get_size())
				var used := image.get_used_rect()
				bounds = used if bounds.size == Vector2i.ZERO else bounds.merge(used)
			assert(bounds.has_area(), "Every authored span paints something")
			# A transparent texel protects the edge coverage of subpixel vector strokes from
			# the SVG rasterizer's viewport clip; original canvas edges remain clipped as authored.
			bounds = bounds.grow(1).intersection(canvas)
			for frame in layer.frames.size():
				var source: String = layer.frames[frame]
				for attribute: String in ["width", "height", "viewBox"]:
					var regex := RegEx.new()
					assert(regex.compile(' ' + attribute + '="[^"]*"') == OK)
					var value := str(bounds.size.x if attribute == "width" else bounds.size.y)
					if attribute == "viewBox":
						value = "%d %d %d %d" % [bounds.position.x, bounds.position.y,
								bounds.size.x, bounds.size.y]
					source = regex.sub(source, ' ' + attribute + '="' + value + '"', false)
				var suffix := "_b" if frame else ""
				var path := staging.path_join("art/events/%s%s.svg" % [layer.name, suffix])
				var file := FileAccess.open(path, FileAccess.WRITE)
				assert(file != null)
				file.store_string("<!-- Generated by tools/split-scenes.py; do not edit. "
						+ "Registered crop from %s, painter-order span. -->\n" % stem
						+ source + "\n")
				file.close()
			entries.append([layer.name, bounds.position.x, bounds.position.y,
					bounds.size.x, bounds.size.y, layer.moving])
		output.layers[stem] = entries
	var file := FileAccess.open(metadata_path, FileAccess.WRITE)
	assert(file != null)
	file.store_string(JSON.stringify(output, "  ") + "\n")
	file.close()
	quit()
