#!/usr/bin/env bash
# Render the trailer from the game itself, frame-locked, from the checked-in shot list.
#
#   tools/trailer.sh                  # every shot, joined -> build/trailer/trailer.mp4
#   tools/trailer.sh --shot choice    # one shot alone     -> build/trailer/shot-choice.mp4
#   tools/trailer.sh --check choice   # render it twice and compare every frame's hash
#   tools/trailer.sh --check all      # the same for every shot
#   tools/trailer.sh --list           # print the shot list and render nothing
#
# PLAYTEST-139: "we can use recordings from a frame locked game. the trailer will be a set of
# paths in pre determined seeds with fixed events so we can reproduce it easily" · "we need to be
# careful not to directly check in either the images or the video so it should be possible to
# run by me and I can generate the video myself. so the setting scripts need to produce the same
# output every time."
#
# Each shot in tools/trailer/shots.json is one Godot launch through its own movie writer
# (`--write-movie <tmp>/frame.png --fixed-fps <fps>`): the game runs frame-locked -- every frame
# advances the clock by exactly 1/fps however long it takes to draw and save -- and writes one PNG
# per frame plus `frame.wav`, the game's own audio mixed at the same clock. The shot's cut is
# taken out of those frames, faded in and out of black and encoded, and the frames are deleted
# before the next shot starts. Editorial cards, end copy and the original oscillator score are
# generated by ffmpeg from the same checked-in shot list; captured game audio stays audible under
# that score. The shots are then joined into one H.264/AAC file. Everything this
# writes is under build/ (gitignored) or a temporary directory it removes, and it fails, naming the
# paths, if the working tree's own status changed while it ran.
#
# The window opens at the game's own resolution (project.godot's viewport size), takes no focus
# and hears no stray key: the movie writer (`--write-movie`) makes DevFlags.recording() true, which
# is itself one of is_rig()'s conditions, so the game's M195 lockdown applies without any dev flag
# of its own, and the same focus guard tools/shot.sh uses hands focus straight back. Every shot also
# carries `--player-view`, so the frame is the release build's own HUD with the debug readout off
# rather than a rig's, and `--no-focus-pause`, since a window that never has real OS focus in the
# first place would otherwise open the pause screen on its own first frame and every frame shows
# that instead of the day it was sent to render. A shot is killed from outside if it outlives the
# movie writer's own deadline
# (see rig_kill_after_movie_seconds in tools/lib_dev_flags.sh).
set -euo pipefail

GODOT="${GODOT:-/Applications/Godot.app/Contents/MacOS/Godot}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHOTS_FILE="$PROJECT_DIR/tools/trailer/shots.json"
OUT_DIR="$PROJECT_DIR/build/trailer"
# shellcheck source=tools/lib_dev_flags.sh
source "$PROJECT_DIR/tools/lib_dev_flags.sh"
# shellcheck source=tools/lib_movie_evidence.sh
source "$PROJECT_DIR/tools/lib_movie_evidence.sh"
# shellcheck source=tools/lib_disk_headroom.sh
source "$PROJECT_DIR/tools/lib_disk_headroom.sh"

usage() {
    cat <<EOF
usage: tools/trailer.sh [--help|-h] [--list | --validate | --shot NAME | --check NAME|all | --check-load NAME|all]

Renders the trailer from tools/trailer/shots.json: gameplay shots through Godot's movie writer,
frame-locked, at the game's own resolution with its audio; editorial cards and the deterministic
oscillator score through ffmpeg; then fades, mixes, joins and encodes them. Frames are deleted as
soon as each shot is encoded. Output goes to build/trailer/ (gitignored).

  (no flag)        render every shot and join them into build/trailer/trailer.mp4
  --shot NAME      render one shot alone into build/trailer/shot-NAME.mp4
  --check NAME     render the shot twice and compare every frame's hash; exits non-zero on a
                   difference inside the shot's cut
  --check all      the same for every shot in the list
  --check-load NAME|all  compare an ordinary render with one under a CPU load worker
  --validate       headlessly validate every recipe; never open a recording window
  --list           print the shot list (name, kind, source, length, gap); render nothing

Disk: frames stay on disk until each shot is encoded, so this refuses to start unless the volume
holding \$TMPDIR has the record-second estimate (tools/lib_disk_headroom.sh) free for every game
second of the shots asked for (an upper bound, as only one shot's frames exist at a time), and warns
when that leaves less than the reserve. A stale atlas repair is checked the same way.

Checks retain hashes, manifests and settings in build/trailer/checks/. Simulation observations
and audio must match too; editorial cards compare decoded frame and silence hashes. Equality applies only to
the recorded engine, assets, ffmpeg/font, and settings named by the retained manifests.

  tools/trailer.sh --shot choice

Opens a window for each gameplay shot. Needs jq, ffmpeg and fc-match on PATH, and Godot 4.7 at \$GODOT.
EOF
}

MODE="all"
TARGET=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h) usage; exit 0 ;;
        --list|--validate)
            [[ "$MODE" == "all" ]] || { echo "$1 cannot be combined with --$MODE" >&2; usage >&2; exit 1; }
            MODE="${1#--}"; shift ;;
        --shot|--check|--check-load)
            [[ "$MODE" == "all" ]] || { echo "$1 cannot be combined with --$MODE" >&2; usage >&2; exit 1; }
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "$1 is missing its shot name" >&2; echo >&2; usage >&2; exit 1
            fi
            MODE="${1#--}"; TARGET="$2"; shift 2 ;;
        *)
            echo "unrecognized argument: $1" >&2; echo >&2; usage >&2; exit 1 ;;
    esac
done

for tool in jq; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "trailer.sh: $tool not found on PATH" >&2
        exit 127
    fi
done
if [[ ! -f "$SHOTS_FILE" ]]; then
    echo "trailer.sh: no shot list at ${SHOTS_FILE#"$PROJECT_DIR"/}" >&2
    exit 1
fi

# ------------------------------------------------------------------- the shot list, checked ---
# Every shot is checked before any window opens: the fields a shot must carry, the dev flags it
# forwards (against the game's own DEV_FLAG_TABLE, the same way run.sh and shot.sh check theirs),
# and the whole cut against the list's own `max_seconds` -- PLAYTEST-139's "30s should be max".
schema_errors="$(jq -r '
    def num: type == "number";
    (if (keys - ["fps","max_seconds","fade","style","score","shots"] | length) == 0
        then empty else "unknown top-level field" end),
    (if (.fps | num) and .fps > 0 and .fps == (.fps | floor) then empty
        else "fps must be a positive integer" end),
    (if (.max_seconds | num) and .max_seconds > 0 and .max_seconds <= 30 then empty
        else "max_seconds must be positive and at most 30" end),
    (if (.shots | type) == "array" and (.shots | length) > 0 then empty
        else "shots must be a non-empty array" end),
    (if (.style | type) == "object" and
        (.style | keys - ["font_family","card_background","paper","ink","accent"] | length) == 0 and
        all([.style.font_family,.style.card_background,.style.paper,.style.ink,.style.accent][];
            type == "string" and length > 0)
        then empty else "style must name the font and three colors" end),
    (if (.score | type) == "object" and
        (.score | keys - ["game_gain","notes"] | length) == 0 and
        (.score.game_gain | num) and .score.game_gain >= 0 and .score.game_gain <= 1 and
        (.score.notes | type) == "array" and (.score.notes | length) > 0 and
        all(.score.notes[];
            (keys - ["at","duration","frequency","gain"] | length) == 0 and
            (.at | num) and .at >= 0 and (.duration | num) and .duration > 0 and
            (.frequency | num) and .frequency > 0 and (.gain | num) and .gain > 0 and .gain <= 0.25)
        then empty else "score must contain bounded deterministic notes and a game_gain" end),
    ((.shots // [])[] |
        (.name // "?") as $n |
        (.kind // "scene") as $kind |
        (if (.name | type) == "string" and (.name | test("^[a-z0-9-]+$")) then empty
            else "a shot name must be lower-case letters, digits and dashes: \($n)" end),
        (if $kind == "scene" or $kind == "card" then empty
            else "\($n): kind must be scene or card" end),
        (if $kind == "scene" and (.recipe | type) == "string" and
                (.recipe | test("^scene-recipes/[a-z0-9-]+\\.json$")) and (.card == null)
            then empty
            elif $kind == "card" and (.recipe == null) and (.in == null) and
                (.card | type) == "object" and
                (.card | keys - ["text","font_size","subtitle","subtitle_font_size","asset"] | length) == 0 and
                (((.card.asset | type) == "string" and (.card.asset | test("^art/[a-z0-9/_-]+\\.png$")) and
                    .card.text == null and .card.font_size == null and .card.subtitle == null and
                    .card.subtitle_font_size == null) or
                 ((.card.text | type) == "string" and (.card.text | length) > 0 and
                    (.card.font_size | num) and .card.font_size > 0 and .card.asset == null and
                    ((.card.subtitle == null and .card.subtitle_font_size == null) or
                     ((.card.subtitle | type) == "string" and (.card.subtitle | length) > 0 and
                      (.card.subtitle_font_size | num) and .card.subtitle_font_size > 0))))
            then empty
            else "\($n): scene shots need a recipe; card shots need text and font_size" end),
        (if (keys - ["name","kind","recipe","card","ending","motion","length","in","gap","fade_in","fade_out"] | length) == 0
            then empty else "\($n): unknown shot field (setup and playback belong in the recipe)" end),
        (if .motion == null or (.motion | type) == "boolean" then empty
            else "\($n): motion must be true or false" end),
        (if .ending == null then empty
            elif $kind == "scene" and (.ending | type) == "object" and
                (.ending | keys - ["at","line","url","line_font_size","url_font_size"] | length) == 0 and
                (.ending.at | num) and .ending.at >= 0 and
                all([.ending.line,.ending.url][]; type == "string" and length > 0) and
                all([.ending.line_font_size,.ending.url_font_size][]; num and . > 0)
            then empty else "\($n): ending copy is malformed or belongs to a card" end),
        (if (.length | num) and .length > 0 then empty else "\($n): length must be positive" end),
        (if (.in // 0 | num) and (.in // 0) >= 0 then empty else "\($n): in must be >= 0" end),
        (if (.gap // 0 | num) and (.gap // 0) >= 0 then empty else "\($n): gap must be >= 0" end),
        (if all([(.fade_in // 0.25),(.fade_out // 0.25)][]; num and . >= 0) then empty
            else "\($n): fades must be nonnegative numbers" end)
    ),
    (if ([.shots[]?.name] | length) == ([.shots[]?.name] | unique | length) then empty
        else "two shots share a name" end)
' "$SHOTS_FILE" 2>&1)" || { echo "trailer.sh: ${SHOTS_FILE#"$PROJECT_DIR"/} is not valid JSON" >&2; exit 1; }
if [[ -n "$schema_errors" ]]; then
    echo "trailer.sh: ${SHOTS_FILE#"$PROJECT_DIR"/} is malformed:" >&2
    printf '  %s\n' "$schema_errors" >&2
    exit 1
fi

FPS="$(jq -r '.fps' "$SHOTS_FILE")"
MAX_SECONDS="$(jq -r '.max_seconds' "$SHOTS_FILE")"
DEFAULT_FADE="$(jq -r '.fade // 0.25' "$SHOTS_FILE")"
SHOT_NAMES=()
while IFS= read -r name; do SHOT_NAMES+=("$name"); done < <(jq -r '.shots[].name' "$SHOTS_FILE")

# One field of one shot, or $3 when the shot does not carry it.
shot_field() {
    jq -r --arg n "$1" --arg f "$2" --arg d "${3:-}" \
        '.shots[] | select(.name == $n) | (.[$f] // $d) | tostring' "$SHOTS_FILE"
}

shot_kind() {
    shot_field "$1" kind scene
}

shot_nested_field() {
    jq -r --arg n "$1" --arg o "$2" --arg f "$3" \
        '.shots[] | select(.name == $n) | .[$o][$f] | tostring' "$SHOTS_FILE"
}

# The recipe owns scene setup and playback; the shot only selects the capture deadline.
shot_game_flags() {
    [[ "$(shot_kind "$1")" == scene ]] || return 0
    printf '%s\n' --player-view --no-save --no-focus-pause \
        --recipe "$PROJECT_DIR/$(shot_field "$1" recipe)" --recipe-mode scripted \
        --after "$(shot_render_seconds "$1")"
}

# Run every authored assertion, even when the selected cut ends before the scene does.
shot_render_seconds() {
    local duration
    duration="$(jq -r '.playback.duration // 5' "$PROJECT_DIR/$(shot_field "$1" recipe)")"
    awk -v a="$(shot_field "$1" in 0.5)" -v b="$(shot_field "$1" length)" \
        -v duration="$duration" 'BEGIN { end=a+b; printf "%.3f\n", (end>duration ? end : duration) }'
}

total_seconds="$(jq -r '[.shots[] | (.gap // 0) + .length] | add' "$SHOTS_FILE" |
    awk '{ printf "%.2f\n", $1 }')"
if awk -v t="$total_seconds" -v m="$MAX_SECONDS" 'BEGIN { exit !(t > m + 0.0001) }'; then
    echo "trailer.sh: the shot list runs ${total_seconds}s, over its own max_seconds ($MAX_SECONDS)" >&2
    exit 1
fi
if ! jq -e --argjson total "$total_seconds" '
    all(.score.notes[]; .at + .duration <= $total) and
    all(.shots[] | select(.ending != null); .ending.at < .length)
' "$SHOTS_FILE" >/dev/null; then
    echo "trailer.sh: score notes and ending copy must finish inside the cut" >&2
    exit 1
fi

for name in "${SHOT_NAMES[@]}"; do
    [[ "$(shot_kind "$name")" == scene ]] || continue
    flags=()
    while IFS= read -r word; do flags+=("$word"); done < <(shot_game_flags "$name")
    if ! validate_dev_flags "${flags[@]}"; then
        echo "trailer.sh: shot '$name' forwards a flag the game does not know (see above)" >&2
        exit 1
    fi
done

if [[ "$MODE" == "shot" || "$MODE" == "check" || "$MODE" == "check-load" ]] && [[ "$TARGET" != "all" || "$MODE" == "shot" ]]; then
    found=""
    for name in "${SHOT_NAMES[@]}"; do [[ "$name" == "$TARGET" ]] && found=1; done
    if [[ -z "$found" ]]; then
        echo "trailer.sh: no shot named '$TARGET' in the list (${SHOT_NAMES[*]})" >&2
        exit 1
    fi
fi

if [[ "$MODE" == "list" ]]; then
    printf '%-10s %-10s %-40s %6s %5s\n' shot kind source length gap
    for name in "${SHOT_NAMES[@]}"; do
        source="$(shot_field "$name" recipe '[editorial card]')"
        printf '%-10s %-10s %-40s %6s %5s\n' "$name" "$(shot_kind "$name")" "$source" \
            "$(shot_field "$name" length)" "$(shot_field "$name" gap 0)"
    done
    echo "total ${total_seconds}s of ${MAX_SECONDS}s"
    exit 0
fi

for tool in ffmpeg fc-match; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "trailer.sh: $tool not found on PATH" >&2
        exit 127
    fi
done

if [[ ! -x "$GODOT" ]]; then
    echo "godot not found at $GODOT" >&2
    echo "install Godot 4.7, or point GODOT at your binary:" >&2
    echo "  GODOT=/path/to/Godot tools/trailer.sh" >&2
    exit 127
fi

# The game's own resolution, read where the game declares it.
WIDTH="$(sed -n 's/^window\/size\/viewport_width=//p' "$PROJECT_DIR/project.godot")"
HEIGHT="$(sed -n 's/^window\/size\/viewport_height=//p' "$PROJECT_DIR/project.godot")"
if ! [[ "$WIDTH" =~ ^[0-9]+$ && "$HEIGHT" =~ ^[0-9]+$ ]]; then
    echo "trailer.sh: could not read the viewport size from project.godot" >&2
    exit 1
fi

FONT_FAMILY="$(jq -r '.style.font_family' "$SHOTS_FILE")"
FONT_FILE="$(fc-match -f '%{file}\n' "$FONT_FAMILY" | head -1)"
if [[ -z "$FONT_FILE" || ! -f "$FONT_FILE" ]]; then
    echo "trailer.sh: fontconfig could not resolve the editorial font '$FONT_FAMILY'" >&2
    exit 1
fi
if [[ "$FONT_FILE" == *":"* || "$FONT_FILE" == *"'"* ]]; then
    echo "trailer.sh: the resolved editorial font path cannot be passed safely to ffmpeg: $FONT_FILE" >&2
    exit 1
fi
PAPER="$(jq -r '.style.paper' "$SHOTS_FILE")"
INK="$(jq -r '.style.ink' "$SHOTS_FILE")"
ACCENT="$(jq -r '.style.accent' "$SHOTS_FILE")"
CARD_BACKGROUND="$(jq -r '.style.card_background' "$SHOTS_FILE")"

while IFS= read -r asset; do
    if [[ ! -f "$PROJECT_DIR/$asset" ]] || ! git -C "$PROJECT_DIR" ls-files --error-unmatch "$asset" >/dev/null 2>&1; then
        echo "trailer.sh: editorial card asset is absent or untracked: $asset" >&2
        exit 1
    fi
done < <(jq -r '.shots[].card.asset? // empty' "$SHOTS_FILE")

# The baked atlas pages, repaired the way tools/shot.sh repairs them -- see its own comment.
if ! "$PROJECT_DIR/tools/bake-atlases.sh" --check >/dev/null 2>&1; then
    "$PROJECT_DIR/tools/bake-atlases.sh" --check >&2 || true
    headroom_preflight tools/trailer.sh "$PROJECT_DIR/.godot" "" import || exit 1
    echo "rebuilding with tools/check.sh -- this takes a few seconds" >&2
    if ! "$PROJECT_DIR/tools/check.sh" >/dev/null; then
        echo "tools/check.sh failed; run it directly to see why" >&2
        exit 1
    fi
fi

# ------------------------------------------------------------------------------ rendering ---
WORK="$(mktemp -d "${TMPDIR:-/tmp}/nappy-trailer.XXXXXX")"
FOCUS_WATCHER_PID=""
LOAD_PID=""
cleanup() {
    [[ -z "$LOAD_PID" ]] || kill "$LOAD_PID" 2>/dev/null || true
    rig_focus_watch_stop "$FOCUS_WATCHER_PID"
    rm -rf "$WORK"
}
trap cleanup EXIT

TREE_BEFORE="$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null || true)"

# Validate the game's resolved normal classification before opening any movie window.
targets=("${SHOT_NAMES[@]}")
[[ -z "$TARGET" || "$TARGET" == all ]] || targets=("$TARGET")
mkdir -p "$WORK/preflight"
recipe_count=0
for name in "${targets[@]}"; do
    [[ "$(shot_kind "$name")" == scene ]] || continue
    recipe="$(shot_field "$name" recipe)"
    if [[ ! -f "$PROJECT_DIR/$recipe" ]] || ! git -C "$PROJECT_DIR" ls-files --error-unmatch "$recipe" >/dev/null 2>&1; then
        echo "trailer.sh: recipe is absent or untracked: $recipe" >&2; exit 1
    fi
    movie_recipe_preflight "$PROJECT_DIR/$recipe" "$WORK/preflight/$name.json" true scripted
    recipe_count=$(( recipe_count + 1 ))
done
if [[ "$MODE" == validate ]]; then
    mkdir -p "$OUT_DIR/validation"
    cp "$WORK/preflight/"*.json "$OUT_DIR/validation/"
    echo "validated ${recipe_count} normal scene recipes and the editorial configuration"
    exit 0
fi

# The whole render is the batch, checked before the first movie window opens. A shot's frames are
# deleted once it is encoded, so the peak is the largest shot's, but the estimate charges the
# summed render seconds of every shot asked for -- an upper bound, like every estimate in
# tools/lib_disk_headroom.sh -- at its record-second rate. Validation writes no frames.
render_seconds_total="$(for name in "${targets[@]}"; do
    [[ "$(shot_kind "$name")" == scene ]] || continue
    shot_render_seconds "$name"
done |
    awk '{ s += $1 } END { printf "%d\n", (s == int(s)) ? s : int(s) + 1 }')"
if [[ "$render_seconds_total" -gt 0 ]]; then
    headroom_preflight tools/trailer.sh "$WORK" \
        "render fewer shots: --shot NAME renders one, and the shot list's lengths set the rest" \
        "record-second:$render_seconds_total" || exit 1
fi

# Renders shot $1's frames and audio into directory $2 (created empty). Fails loudly if Godot
# did not quit on its own or did not write the frames the cut needs.
render_frames() {
    local name="$1" dir="$2" after kill_after flags=()
    rm -rf "$dir"; mkdir -p "$dir"
    while IFS= read -r word; do flags+=("$word"); done < <(shot_game_flags "$name")
    flags+=(--recipe-manifest "$dir/manifest.json")
    after="$(shot_render_seconds "$name")"
    kill_after="$(rig_kill_after_movie_seconds --after "$after")"
    echo "rendering '$name' (${after}s of game at ${FPS}fps)..." >&2
    local noted
    noted="$(rig_focus_note)"
    "$GODOT" --path "$PROJECT_DIR" --resolution "${WIDTH}x${HEIGHT}" --disable-vsync \
        --write-movie "$dir/frame.png" --fixed-fps "$FPS" \
        -- "${flags[@]}" > "$dir/godot.log" 2>&1 &
    local pid=$!
    FOCUS_WATCHER_PID="$(rig_focus_watch_start "$pid" "$noted")"
    if ! wait_or_kill "$pid" "$kill_after"; then
        rig_focus_watch_stop "$FOCUS_WATCHER_PID"; FOCUS_WATCHER_PID=""
        echo "trailer.sh: killed Godot after ${kill_after}s rendering '$name' -- it did not quit" >&2
        tail -20 "$dir/godot.log" >&2
        return 1
    fi
    rig_focus_watch_stop "$FOCUS_WATCHER_PID"; FOCUS_WATCHER_PID=""
    if [[ "$WAIT_OR_KILL_STATUS" -ne 0 ]]; then
        echo "trailer.sh: Godot exited $WAIT_OR_KILL_STATUS rendering '$name'" >&2
        tail -20 "$dir/godot.log" >&2
        return 1
    fi
    if grep -qE '^(SCRIPT )?ERROR' "$dir/godot.log"; then
        echo "trailer.sh: '$name' printed an engine error while rendering:" >&2
        grep -E -A2 '^(SCRIPT )?ERROR' "$dir/godot.log" | head -20 >&2
        return 1
    fi
    movie_manifest_check "$dir/manifest.json" true || return 1
    movie_playback_check "$dir/manifest.json" || return 1
    local need last
    need="$(awk -v a="$(shot_field "$name" in 0.5)" -v b="$(shot_field "$name" length)" \
        -v f="$FPS" 'BEGIN { printf "%d\n", int((a + b) * f + 0.5) }')"
    last="$(printf '%s/frame%08d.png' "$dir" "$((need - 1))")"
    if [[ ! -f "$last" ]]; then
        echo "trailer.sh: '$name' wrote too few frames (no $(basename "$last"))" >&2
        return 1
    fi
    visible_motion_check "$name" "$dir"
}

# A manifest proves that the recipe advanced; this proves that the selected pixels did too. The
# half-second ceiling permits a deliberate held pose while rejecting the stale viewport texture a
# covered macOS movie-writer window otherwise repeats for the rest of a live scene.
visible_motion_check() {
    local name="$1" dir="$2"
    [[ "$(shot_field "$name" motion false)" == true ]] || return 0
    local start count end frame file hash previous="" run=0 longest=0
    start="$(awk -v a="$(shot_field "$name" in 0.5)" -v f="$FPS" \
        'BEGIN { printf "%d\n", int(a * f + 0.5) }')"
    count="$(awk -v a="$(shot_field "$name" length)" -v f="$FPS" \
        'BEGIN { printf "%d\n", int(a * f + 0.5) }')"
    end=$(( start + count ))
    for (( frame=start; frame<end; frame++ )); do
        file="$(printf '%s/frame%08d.png' "$dir" "$frame")"
        hash="$(shasum -a 256 < "$file" | awk '{print $1}')"
        if [[ "$hash" == "$previous" ]]; then
            run=$(( run + 1 ))
        else
            run=1
            previous="$hash"
        fi
        (( run > longest )) && longest="$run"
    done
    if (( longest > FPS / 2 )); then
        echo "trailer.sh: '$name' has $longest consecutive identical selected frames; its visible motion froze" >&2
        return 1
    fi
}

# Encodes shot $1's cut out of the frames in $2 into $3: trimmed to [in, in + length], faded in
# from and out to black, preceded by `gap` seconds of black and silence.
encode_shot() {
    local name="$1" dir="$2" out="$3"
    local in length gap fade_in fade_out start count
    in="$(shot_field "$name" in 0.5)"
    length="$(shot_field "$name" length)"
    gap="$(shot_field "$name" gap 0)"
    fade_in="$(shot_field "$name" fade_in "$DEFAULT_FADE")"
    fade_out="$(shot_field "$name" fade_out "$DEFAULT_FADE")"
    start="$(awk -v a="$in" -v f="$FPS" 'BEGIN { printf "%d\n", int(a * f + 0.5) }')"
    count="$(awk -v a="$length" -v f="$FPS" 'BEGIN { printf "%d\n", int(a * f + 0.5) }')"
    local out_start total
    out_start="$(awk -v l="$length" -v o="$fade_out" 'BEGIN { printf "%.4f\n", l - o }')"
    total="$(awk -v l="$length" -v g="$gap" 'BEGIN { printf "%.4f\n", l + g }')"
    local audio=(-f lavfi -i "anullsrc=r=48000:cl=stereo")
    [[ -f "$dir/frame.wav" ]] && audio=(-i "$dir/frame.wav")
    local gap_ms
    gap_ms="$(awk -v g="$gap" 'BEGIN { printf "%d\n", int(g * 1000 + 0.5) }')"
    local video_filters="trim=end_frame=${count},setpts=PTS-STARTPTS"
    if jq -e --arg n "$name" '.shots[] | select(.name == $n) | .ending != null' "$SHOTS_FILE" >/dev/null; then
        local ending_at line_size url_size
        ending_at="$(shot_nested_field "$name" ending at)"
        line_size="$(shot_nested_field "$name" ending line_font_size)"
        url_size="$(shot_nested_field "$name" ending url_font_size)"
        shot_nested_field "$name" ending line > "$dir/ending-line.txt"
        shot_nested_field "$name" ending url > "$dir/ending-url.txt"
        video_filters+=",drawtext=fontfile='${FONT_FILE}':textfile='${dir}/ending-line.txt':"
        video_filters+="fontsize=${line_size}:fontcolor=${INK}:box=1:boxcolor=${PAPER}@0.82:boxborderw=16:"
        video_filters+="x=(w-text_w)/2:y=h*0.075:alpha='min(1\\,max(0\\,(t-${ending_at})/0.45))'"
        video_filters+=",drawtext=fontfile='${FONT_FILE}':textfile='${dir}/ending-url.txt':"
        video_filters+="fontsize=${url_size}:fontcolor=${INK}:box=1:boxcolor=${PAPER}@0.82:boxborderw=11:"
        video_filters+="x=(w-text_w)/2:y=h*0.165:alpha='min(1\\,max(0\\,(t-${ending_at})/0.45))'"
    fi
    video_filters+=",fade=t=in:st=0:d=${fade_in},fade=t=out:st=${out_start}:d=${fade_out}"
    local video_graph="[0:v]${video_filters},format=yuv420p[v];"
    if awk -v g="$gap" 'BEGIN { exit !(g > 0) }'; then
        # A separate finite black source keeps the gap in the video timeline. `tpad` after
        # `trim=end_frame` is silently cut back to the image sequence's input duration by ffmpeg's
        # output sync, even while the padded audio retains it.
        video_graph="color=c=black:s=${WIDTH}x${HEIGHT}:r=${FPS}:d=${gap}[gapv];\
[0:v]${video_filters}[shotv];[gapv][shotv]concat=n=2:v=1:a=0,format=yuv420p[v];"
    fi
    ffmpeg -hide_banner -loglevel error -y \
        -framerate "$FPS" -start_number "$start" -i "$dir/frame%08d.png" "${audio[@]}" \
        -filter_complex "\
${video_graph}\
[1:a]atrim=start=${in}:duration=${length},asetpts=PTS-STARTPTS,aformat=sample_rates=48000:channel_layouts=stereo,\
afade=t=in:st=0:d=${fade_in},afade=t=out:st=${out_start}:d=${fade_out},\
adelay=${gap_ms}:all=1,apad,atrim=duration=${total}[a]" \
        -map "[v]" -map "[a]" -r "$FPS" -c:v libx264 -preset veryfast -crf 12 \
        -c:a pcm_s16le "$out"
}

# Produces a warm paper-and-ink editorial card from the checked-in text. The resolved font and its
# hash are retained beside the final trailer so a different host font cannot be mistaken for the
# same edit.
encode_card() {
    local name="$1" out="$2"
    local length gap fade_in fade_out out_start total gap_ms asset
    length="$(shot_field "$name" length)"
    gap="$(shot_field "$name" gap 0)"
    fade_in="$(shot_field "$name" fade_in "$DEFAULT_FADE")"
    fade_out="$(shot_field "$name" fade_out "$DEFAULT_FADE")"
    out_start="$(awk -v l="$length" -v o="$fade_out" 'BEGIN { printf "%.4f\n", l - o }')"
    total="$(awk -v l="$length" -v g="$gap" 'BEGIN { printf "%.4f\n", l + g }')"
    gap_ms="$(awk -v g="$gap" 'BEGIN { printf "%d\n", int(g * 1000 + 0.5) }')"
    asset="$(shot_nested_field "$name" card asset)"
    if [[ "$asset" != null ]]; then
        ffmpeg -hide_banner -loglevel error -y \
            -f lavfi -i "color=c=${CARD_BACKGROUND}:s=${WIDTH}x${HEIGHT}:r=${FPS}:d=${length}" \
            -f lavfi -i "anullsrc=r=48000:cl=stereo" \
            -loop 1 -framerate "$FPS" -t "$length" -i "$PROJECT_DIR/$asset" \
            -filter_complex "\
[0:v][2:v]overlay=x=(W-w)/2:y=(H-h)/2:shortest=1:format=auto,\
fade=t=in:st=0:d=${fade_in},fade=t=out:st=${out_start}:d=${fade_out},\
tpad=start_duration=${gap}:color=black,format=yuv420p[v];\
[1:a]atrim=duration=${length},asetpts=PTS-STARTPTS,afade=t=in:st=0:d=${fade_in},\
afade=t=out:st=${out_start}:d=${fade_out},adelay=${gap_ms}:all=1,apad,atrim=duration=${total}[a]" \
            -map "[v]" -map "[a]" -r "$FPS" -c:v libx264 -preset veryfast -crf 12 \
            -c:a pcm_s16le "$out"
        return
    fi
    local font_size subtitle subtitle_size text_file subtitle_file
    font_size="$(shot_nested_field "$name" card font_size)"
    subtitle="$(shot_nested_field "$name" card subtitle)"
    subtitle_size="$(shot_nested_field "$name" card subtitle_font_size)"
    text_file="$WORK/card-${name}.txt"
    subtitle_file="$WORK/card-${name}-subtitle.txt"
    shot_nested_field "$name" card text > "$text_file"
    [[ "$subtitle" == null ]] || printf '%s\n' "$subtitle" > "$subtitle_file"
    local card_filters="drawtext=fontfile='${FONT_FILE}':textfile='${text_file}':"
    card_filters+="fontsize=${font_size}:fontcolor=${PAPER}:x=(w-text_w)/2:y=h*0.29"
    if [[ "$subtitle" != null ]]; then
        card_filters+=",drawtext=fontfile='${FONT_FILE}':textfile='${subtitle_file}':"
        card_filters+="fontsize=${subtitle_size}:fontcolor=${PAPER}@0.86:x=(w-text_w)/2:y=h*0.63"
    fi
    ffmpeg -hide_banner -loglevel error -y \
        -f lavfi -i "color=c=${CARD_BACKGROUND}:s=${WIDTH}x${HEIGHT}:r=${FPS}:d=${length}" \
        -f lavfi -i "anullsrc=r=48000:cl=stereo" \
        -filter_complex "\
[0:v]${card_filters},fade=t=in:st=0:d=${fade_in},fade=t=out:st=${out_start}:d=${fade_out},\
tpad=start_duration=${gap}:color=black,format=yuv420p[v];\
[1:a]atrim=duration=${length},asetpts=PTS-STARTPTS,afade=t=in:st=0:d=${fade_in},\
afade=t=out:st=${out_start}:d=${fade_out},adelay=${gap_ms}:all=1,apad,atrim=duration=${total}[a]" \
        -map "[v]" -map "[a]" -r "$FPS" -c:v libx264 -preset veryfast -crf 12 \
        -c:a pcm_s16le "$out"
}

# Joins the encoded shots named after $1 into the final file $OUTPUT. The full cut mixes the
# deterministic score under captured game audio; isolated --shot renders retain only their own
# game audio so a scene can be inspected without music from another point in the timeline.
join_shots() {
    local include_score="$1"
    shift
    local inputs=() streams="" i=0
    for f in "$@"; do
        inputs+=(-i "$f")
        streams+="[$i:v][$i:a]"
        i=$(( i + 1 ))
    done
    mkdir -p "$(dirname "$OUTPUT")"
    if [[ "$include_score" == true ]]; then
        local score_expression game_gain score_index
        score_expression="$(jq -r '[.score.notes[] |
            "if(between(t\\,\(.at)\\,\(.at + .duration))\\,\(.gain)*sin(2*PI*\(.frequency)*(t-\(.at)))*pow(sin(PI*(t-\(.at))/\(.duration))\\,2)\\,0)"
            ] | join("+")' "$SHOTS_FILE")"
        game_gain="$(jq -r '.score.game_gain' "$SHOTS_FILE")"
        score_index="$i"
        inputs+=(-f lavfi -i "aevalsrc=exprs='${score_expression}|${score_expression}':s=48000:d=${total_seconds}:c=stereo")
        ffmpeg -hide_banner -loglevel error -y "${inputs[@]}" \
            -filter_complex "${streams}concat=n=${i}:v=1:a=1[joinedv][gamea];\
[gamea]volume=${game_gain}[gamebed];[${score_index}:a]aformat=sample_rates=48000:channel_layouts=stereo[score];\
[gamebed][score]amix=inputs=2:duration=first:normalize=0,alimiter=limit=0.92[a]" \
            -map "[joinedv]" -map "[a]" -r "$FPS" -c:v libx264 -preset slow -crf 18 -pix_fmt yuv420p \
            -c:a aac -b:a 192k -movflags +faststart "$OUTPUT"
    else
        ffmpeg -hide_banner -loglevel error -y "${inputs[@]}" \
            -filter_complex "${streams}concat=n=${i}:v=1:a=1[v][a]" \
            -map "[v]" -map "[a]" -r "$FPS" -c:v libx264 -preset slow -crf 18 -pix_fmt yuv420p \
            -c:a aac -b:a 192k -movflags +faststart "$OUTPUT"
    fi
}

check_shot() {
    local name="$1" a="$WORK/check-a" b="$WORK/check-b"
    local evidence="$OUT_DIR/checks/$name/$MODE"
    render_frames "$name" "$a" || return 1
    movie_evidence "$a" "$evidence/a" "$FPS" ordinary || return 1
    cp "$evidence/a/frames.sha256" "$WORK/hash-a"
    if [[ "$TARGET" == all ]]; then
        encode_shot "$name" "$a" "$WORK/editor-a-${name}.mkv" || return 1
    fi
    local audio_a=""
    [[ -f "$a/frame.wav" ]] && audio_a="$(shasum -a 1 < "$a/frame.wav")"
    rm -rf "$a"
    if [[ "$MODE" == check-load ]]; then
        awk 'BEGIN { x=1; while (1) { x=(x+1)%1000003 } }' >/dev/null &
        LOAD_PID=$!
    fi
    if ! render_frames "$name" "$b"; then
        [[ -z "$LOAD_PID" ]] || kill "$LOAD_PID" 2>/dev/null || true
        LOAD_PID=""; return 1
    fi
    [[ -z "$LOAD_PID" ]] || kill "$LOAD_PID" 2>/dev/null || true
    LOAD_PID=""
    movie_evidence "$b" "$evidence/b" "$FPS" "$MODE" || return 1
    cp "$evidence/b/frames.sha256" "$WORK/hash-b"
    if [[ "$TARGET" == all ]]; then
        encode_shot "$name" "$b" "$WORK/editor-b-${name}.mkv" || return 1
    fi
    local audio_b=""
    [[ -f "$b/frame.wav" ]] && audio_b="$(shasum -a 1 < "$b/frame.wav")"
    rm -rf "$b"
    jq -S . "$evidence/a/manifest.json" > "$WORK/manifest-a"
    jq -S . "$evidence/b/manifest.json" > "$WORK/manifest-b"
    local simulation_match=true
    if ! diff -u "$WORK/manifest-a" "$WORK/manifest-b" > "$evidence/manifest.diff"; then
        simulation_match=false
        echo "check '$name': resolved setup or simulation observations differ; see $evidence/manifest.diff"
    fi
    jq -S 'del(.label)' "$evidence/a/settings.json" > "$WORK/settings-a"
    jq -S 'del(.label)' "$evidence/b/settings.json" > "$WORK/settings-b"
    local settings_match=true
    diff -u "$WORK/settings-a" "$WORK/settings-b" > "$evidence/settings.diff" || settings_match=false
    if [[ -f "$evidence/a/atlases.sha256" || -f "$evidence/b/atlases.sha256" ]]; then
        diff -u "$evidence/a/atlases.sha256" "$evidence/b/atlases.sha256" > "$evidence/atlases.diff" || settings_match=false
    fi
    local start end total differ in_cut first
    start="$(awk -v a="$(shot_field "$name" in 0.5)" -v f="$FPS" 'BEGIN { printf "%d\n", int(a * f + 0.5) }')"
    end="$(awk -v a="$(shot_field "$name" in 0.5)" -v b="$(shot_field "$name" length)" -v f="$FPS" \
        'BEGIN { printf "%d\n", int((a + b) * f + 0.5) }')"
    total="$(wc -l < "$WORK/hash-a" | tr -d ' ')"
    # Frames present in one render and not the other count as differences too.
    differ="$(diff "$WORK/hash-a" "$WORK/hash-b" | grep -E '^[<>]' | awk '{print $3}' | sort -u || true)"
    in_cut=0
    first=""
    while IFS= read -r frame; do
        [[ -z "$frame" ]] && continue
        [[ -z "$first" ]] && first="$frame"
        local n=$(( 10#$(printf '%s' "$frame" | tr -dc '0-9') ))
        if (( n >= start && n < end )); then in_cut=$(( in_cut + 1 )); fi
    done <<< "$differ"
    local n_differ
    n_differ="$(printf '%s' "$differ" | grep -c . || true)"
    local audio_note="audio identical"
    [[ "$audio_a" != "$audio_b" ]] && audio_note="audio DIFFERS"
    if [[ "$n_differ" -eq 0 ]]; then
        echo "check '$name': $total frames, every one identical; $audio_note"
    else
        echo "check '$name': $n_differ of $total frames differ ($in_cut inside the cut," \
            "frames $start-$((end - 1))); first: $first; $audio_note"
    fi
    local passed=false
    [[ "$in_cut" -eq 0 && "$audio_a" == "$audio_b" && "$simulation_match" == true && "$settings_match" == true ]] && passed=true
    jq -n --argjson passed "$passed" --argjson simulation_match "$simulation_match" \
        --argjson cut_frame_differences "$in_cut" --arg mode "$MODE" \
        --argjson settings_match "$settings_match" \
        --argjson load_workers "$([[ "$MODE" == check-load ]] && echo 1 || echo 0)" \
        --argjson audio_match "$([[ "$audio_a" == "$audio_b" ]] && echo true || echo false)" \
        '{passed:$passed,mode:$mode,simulation_match:$simulation_match,settings_match:$settings_match,
          second_render_cpu_load_workers:$load_workers,
          cut_frame_differences:$cut_frame_differences,audio_match:$audio_match}' > "$evidence/result.json"
    [[ "$passed" == true ]]
}

check_card() {
    local name="$1" a="$WORK/card-a.mkv" b="$WORK/card-b.mkv"
    local evidence="$OUT_DIR/checks/$name/$MODE"
    mkdir -p "$evidence"
    encode_card "$name" "$a" || return 1
    [[ "$TARGET" != all ]] || cp "$a" "$WORK/editor-a-${name}.mkv"
    ffmpeg -hide_banner -loglevel error -y -i "$a" -map 0:v -f framehash -hash sha256 "$WORK/card-a.frames"
    ffmpeg -hide_banner -loglevel error -y -i "$a" -map 0:a -f hash -hash sha256 "$WORK/card-a.audio"
    if [[ "$MODE" == check-load ]]; then
        awk 'BEGIN { x=1; while (1) { x=(x+1)%1000003 } }' >/dev/null &
        LOAD_PID=$!
    fi
    encode_card "$name" "$b" || return 1
    [[ "$TARGET" != all ]] || cp "$b" "$WORK/editor-b-${name}.mkv"
    [[ -z "$LOAD_PID" ]] || kill "$LOAD_PID" 2>/dev/null || true
    LOAD_PID=""
    ffmpeg -hide_banner -loglevel error -y -i "$b" -map 0:v -f framehash -hash sha256 "$WORK/card-b.frames"
    ffmpeg -hide_banner -loglevel error -y -i "$b" -map 0:a -f hash -hash sha256 "$WORK/card-b.audio"
    local passed=false
    if diff -u "$WORK/card-a.frames" "$WORK/card-b.frames" > "$evidence/frames.diff" \
        && diff -u "$WORK/card-a.audio" "$WORK/card-b.audio" > "$evidence/audio.diff"; then
        passed=true
    fi
    local asset asset_sha=""
    asset="$(shot_nested_field "$name" card asset)"
    [[ "$asset" == null ]] || asset_sha="$(shasum -a 256 < "$PROJECT_DIR/$asset" | awk '{print $1}')"
    jq -n --argjson passed "$passed" --arg mode "$MODE" --arg asset "$asset" \
        --arg asset_sha256 "$asset_sha" \
        --arg font "$FONT_FILE" --arg font_sha256 "$(shasum -a 256 < "$FONT_FILE" | awk '{print $1}')" \
        '{passed:$passed,mode:$mode,kind:"editorial card",font:$font,font_sha256:$font_sha256,
          asset:(if $asset == "null" then null else $asset end),asset_sha256:$asset_sha256}' \
        > "$evidence/result.json"
    if [[ "$passed" == true ]]; then
        echo "check '$name': editorial card video and silence are identical"
    else
        echo "check '$name': editorial card differs; see $evidence" >&2
    fi
    [[ "$passed" == true ]]
}

check_editor() {
    local evidence="$OUT_DIR/checks/editor/$MODE"
    local saved_output="${OUTPUT:-}" a_parts=() b_parts=() name
    mkdir -p "$evidence"
    for name in "${SHOT_NAMES[@]}"; do
        a_parts+=("$WORK/editor-a-${name}.mkv")
        b_parts+=("$WORK/editor-b-${name}.mkv")
    done
    OUTPUT="$WORK/editor-a.mp4"
    join_shots true "${a_parts[@]}" || return 1
    OUTPUT="$WORK/editor-b.mp4"
    join_shots true "${b_parts[@]}" || return 1
    OUTPUT="$saved_output"
    ffmpeg -hide_banner -loglevel error -y -i "$WORK/editor-a.mp4" -map 0:v \
        -f framehash -hash sha256 "$WORK/editor-a.frames"
    ffmpeg -hide_banner -loglevel error -y -i "$WORK/editor-a.mp4" -map 0:a \
        -f hash -hash sha256 "$WORK/editor-a.audio"
    ffmpeg -hide_banner -loglevel error -y -i "$WORK/editor-b.mp4" -map 0:v \
        -f framehash -hash sha256 "$WORK/editor-b.frames"
    ffmpeg -hide_banner -loglevel error -y -i "$WORK/editor-b.mp4" -map 0:a \
        -f hash -hash sha256 "$WORK/editor-b.audio"
    local video_match=false audio_match=false passed=false
    diff -u "$WORK/editor-a.frames" "$WORK/editor-b.frames" > "$evidence/frames.diff" && video_match=true
    diff -u "$WORK/editor-a.audio" "$WORK/editor-b.audio" > "$evidence/audio.diff" && audio_match=true
    [[ "$video_match" == true && "$audio_match" == true ]] && passed=true
    jq -n --argjson passed "$passed" --argjson video_match "$video_match" \
        --argjson audio_match "$audio_match" --arg mode "$MODE" \
        '{passed:$passed,mode:$mode,scope:"complete editorial composition",
          decoded_video_match:$video_match,decoded_audio_match:$audio_match}' > "$evidence/result.json"
    if [[ "$passed" == true ]]; then
        echo "check 'editor': ending overlays, score and final mix are identical"
    else
        echo "check 'editor': final composition differs; see $evidence" >&2
    fi
    [[ "$passed" == true ]]
}

write_editorial_settings() {
    local revision tree dirty ffmpeg_version font_sha shots_sha card_asset card_asset_sha=""
    revision="$(git -C "$PROJECT_DIR" rev-parse HEAD)"
    tree="$(git -C "$PROJECT_DIR" rev-parse HEAD^{tree})"
    dirty="$(git -C "$PROJECT_DIR" diff HEAD -- | shasum -a 256 | awk '{print $1}')"
    ffmpeg_version="$(ffmpeg -version | head -1)"
    font_sha="$(shasum -a 256 < "$FONT_FILE" | awk '{print $1}')"
    shots_sha="$(shasum -a 256 < "$SHOTS_FILE" | awk '{print $1}')"
    card_asset="$(jq -r '[.shots[].card.asset? // empty][0] // ""' "$SHOTS_FILE")"
    [[ -z "$card_asset" ]] || card_asset_sha="$(shasum -a 256 < "$PROJECT_DIR/$card_asset" | awk '{print $1}')"
    mkdir -p "$OUT_DIR"
    jq -n --arg revision "$revision" --arg tree "$tree" --arg dirty "$dirty" \
        --arg ffmpeg "$ffmpeg_version" --arg font_family "$FONT_FAMILY" --arg font "$FONT_FILE" \
        --arg font_sha256 "$font_sha" --arg shots_sha256 "$shots_sha" \
        --arg card_asset "$card_asset" --arg card_asset_sha256 "$card_asset_sha" \
        --argjson fps "$FPS" --argjson width "$WIDTH" --argjson height "$HEIGHT" \
        --argjson duration "$total_seconds" \
        '{revision:$revision,tracked_tree:$tree,working_diff_sha256:$dirty,ffmpeg:$ffmpeg,
          font_family:$font_family,font:$font,font_sha256:$font_sha256,shots_sha256:$shots_sha256,
          card_asset:$card_asset,card_asset_sha256:$card_asset_sha256,
          fps:$fps,width:$width,height:$height,duration_seconds:$duration,
          score:"deterministic oscillator notes from tools/trailer/shots.json"}' \
        > "$OUT_DIR/editorial-settings.json"
}

# Fails, naming them, if the working tree's status moved while this ran: nothing this writes may
# be something git tracks or would offer to add.
assert_tree_untouched() {
    local after
    after="$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null || true)"
    if [[ "$after" != "$TREE_BEFORE" ]]; then
        echo "trailer.sh: the working tree's status changed while rendering:" >&2
        diff <(printf '%s\n' "$TREE_BEFORE") <(printf '%s\n' "$after") >&2 || true
        return 1
    fi
}

status=0
case "$MODE" in
    check|check-load)
        targets=("$TARGET")
        [[ "$TARGET" == "all" ]] && targets=("${SHOT_NAMES[@]}")
        for name in "${targets[@]}"; do
            if [[ "$(shot_kind "$name")" == card ]]; then
                check_card "$name" || status=1
            else
                check_shot "$name" || status=1
            fi
        done
        if [[ "$TARGET" == all && "$status" -eq 0 ]]; then
            check_editor || status=1
        fi
        ;;
    shot)
        OUTPUT="$OUT_DIR/shot-$TARGET.mp4"
        if [[ "$(shot_kind "$TARGET")" == card ]]; then
            encode_card "$TARGET" "$WORK/00.mkv"
        else
            render_frames "$TARGET" "$WORK/frames"
            movie_evidence "$WORK/frames" "$OUT_DIR/evidence/$TARGET" "$FPS" "$TARGET"
            encode_shot "$TARGET" "$WORK/frames" "$WORK/00.mkv"
            rm -rf "$WORK/frames"
        fi
        join_shots false "$WORK/00.mkv"
        echo "wrote ${OUTPUT#"$PROJECT_DIR"/}"
        ;;
    all)
        OUTPUT="$OUT_DIR/trailer.mp4"
        encoded=()
        i=0
        for name in "${SHOT_NAMES[@]}"; do
            part="$(printf '%s/%02d.mkv' "$WORK" "$i")"
            if [[ "$(shot_kind "$name")" == card ]]; then
                encode_card "$name" "$part"
            else
                render_frames "$name" "$WORK/frames"
                movie_evidence "$WORK/frames" "$OUT_DIR/evidence/$name" "$FPS" "$name"
                encode_shot "$name" "$WORK/frames" "$part"
                rm -rf "$WORK/frames"
            fi
            encoded+=("$part")
            i=$(( i + 1 ))
        done
        join_shots true "${encoded[@]}"
        write_editorial_settings
        echo "wrote ${OUTPUT#"$PROJECT_DIR"/} (${total_seconds}s, ${#SHOT_NAMES[@]} shots)"
        ;;
esac
assert_tree_untouched || status=1
exit "$status"
